### ISSUE TITLE
Team 116 review

### ISSUE THREAD

**Issue by gabrie-lhilarion** [JasemDuncan/members-only#1]
#  Recommendation: 
- Please just follow the instructions in the tutorial. 
- Use gems instead of creating a custom logic.
- If you want to understand better for yourself, you can create a repo or branch for your solo learning.
- One more thing for the project to be approved you need to follow the tutorial.

**Comment by JasemDuncan** [comment]
Ok @gabrie-lhilarion, we are working on that.

**Comment by JasemDuncan** [comment]
Thank you.
